// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: protos/fields/v1/fields.proto

package fields

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field []*Field `protobuf:"bytes,1,rep,name=field,proto3" json:"field,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetField() []*Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Field:
	//	*Field_Text
	//	*Field_Textarea
	//	*Field_Number
	//	*Field_Checkbox
	Field isField_Field `protobuf_oneof:"field"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{1}
}

func (m *Field) GetField() isField_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (x *Field) GetText() *Text {
	if x, ok := x.GetField().(*Field_Text); ok {
		return x.Text
	}
	return nil
}

func (x *Field) GetTextarea() *Textarea {
	if x, ok := x.GetField().(*Field_Textarea); ok {
		return x.Textarea
	}
	return nil
}

func (x *Field) GetNumber() *Number {
	if x, ok := x.GetField().(*Field_Number); ok {
		return x.Number
	}
	return nil
}

func (x *Field) GetCheckbox() *Checkbox {
	if x, ok := x.GetField().(*Field_Checkbox); ok {
		return x.Checkbox
	}
	return nil
}

type isField_Field interface {
	isField_Field()
}

type Field_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Field_Textarea struct {
	Textarea *Textarea `protobuf:"bytes,2,opt,name=textarea,proto3,oneof"`
}

type Field_Number struct {
	Number *Number `protobuf:"bytes,3,opt,name=number,proto3,oneof"`
}

type Field_Checkbox struct {
	Checkbox *Checkbox `protobuf:"bytes,4,opt,name=checkbox,proto3,oneof"`
}

func (*Field_Text) isField_Field() {}

func (*Field_Textarea) isField_Field() {}

func (*Field_Number) isField_Field() {}

func (*Field_Checkbox) isField_Field() {}

type Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Required bool  `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Min      int32 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max      int32 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Custom   bool  `protobuf:"varint,4,opt,name=custom,proto3" json:"custom,omitempty"`
}

func (x *Validator) Reset() {
	*x = Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{2}
}

func (x *Validator) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Validator) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Validator) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Validator) GetCustom() bool {
	if x != nil {
		return x.Custom
	}
	return false
}

type Base struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validator *Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Label     string     `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Help      string     `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
}

func (x *Base) Reset() {
	*x = Base{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{3}
}

func (x *Base) GetValidator() *Validator {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *Base) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Base) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Base) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      *Base  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Default   string `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Minlength int32  `protobuf:"varint,3,opt,name=minlength,proto3" json:"minlength,omitempty"`
	Maxlength int32  `protobuf:"varint,4,opt,name=maxlength,proto3" json:"maxlength,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{4}
}

func (x *Text) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Text) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Text) GetMinlength() int32 {
	if x != nil {
		return x.Minlength
	}
	return 0
}

func (x *Text) GetMaxlength() int32 {
	if x != nil {
		return x.Maxlength
	}
	return 0
}

type Textarea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base    *Base  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Default string `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *Textarea) Reset() {
	*x = Textarea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Textarea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Textarea) ProtoMessage() {}

func (x *Textarea) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Textarea.ProtoReflect.Descriptor instead.
func (*Textarea) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{5}
}

func (x *Textarea) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Textarea) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base    *Base `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Default int32 `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	Min     int32 `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Max     int32 `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	Step    int32 `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{6}
}

func (x *Number) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Number) GetDefault() int32 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *Number) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Number) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Number) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type Checkbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base    *Base `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Default bool  `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *Checkbox) Reset() {
	*x = Checkbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fields_v1_fields_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkbox) ProtoMessage() {}

func (x *Checkbox) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fields_v1_fields_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkbox.ProtoReflect.Descriptor instead.
func (*Checkbox) Descriptor() ([]byte, []int) {
	return file_protos_fields_v1_fields_proto_rawDescGZIP(), []int{7}
}

func (x *Checkbox) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Checkbox) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

var File_protos_fields_v1_fields_proto protoreflect.FileDescriptor

var file_protos_fields_v1_fields_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x22, 0x35, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2d, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xe6, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x38, 0x0a, 0x08, 0x74, 0x65, 0x78, 0x74, 0x61, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x61, 0x72, 0x65, 0x61, 0x48, 0x00,
	0x52, 0x08, 0x74, 0x65, 0x78, 0x74, 0x61, 0x72, 0x65, 0x61, 0x12, 0x32, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38,
	0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x78, 0x48, 0x00, 0x52, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x78, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x63, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x22, 0x7f, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x2a, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x22, 0x50, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74, 0x61, 0x72, 0x65, 0x61, 0x12, 0x2a,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0x50, 0x0a,
	0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x78, 0x12, 0x2a, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42,
	0x19, 0x5a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x2f, 0x76, 0x31, 0x3b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_fields_v1_fields_proto_rawDescOnce sync.Once
	file_protos_fields_v1_fields_proto_rawDescData = file_protos_fields_v1_fields_proto_rawDesc
)

func file_protos_fields_v1_fields_proto_rawDescGZIP() []byte {
	file_protos_fields_v1_fields_proto_rawDescOnce.Do(func() {
		file_protos_fields_v1_fields_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_fields_v1_fields_proto_rawDescData)
	})
	return file_protos_fields_v1_fields_proto_rawDescData
}

var file_protos_fields_v1_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_fields_v1_fields_proto_goTypes = []interface{}{
	(*Spec)(nil),      // 0: protos.fields.v1.Spec
	(*Field)(nil),     // 1: protos.fields.v1.Field
	(*Validator)(nil), // 2: protos.fields.v1.Validator
	(*Base)(nil),      // 3: protos.fields.v1.Base
	(*Text)(nil),      // 4: protos.fields.v1.Text
	(*Textarea)(nil),  // 5: protos.fields.v1.Textarea
	(*Number)(nil),    // 6: protos.fields.v1.Number
	(*Checkbox)(nil),  // 7: protos.fields.v1.Checkbox
}
var file_protos_fields_v1_fields_proto_depIdxs = []int32{
	1,  // 0: protos.fields.v1.Spec.field:type_name -> protos.fields.v1.Field
	4,  // 1: protos.fields.v1.Field.text:type_name -> protos.fields.v1.Text
	5,  // 2: protos.fields.v1.Field.textarea:type_name -> protos.fields.v1.Textarea
	6,  // 3: protos.fields.v1.Field.number:type_name -> protos.fields.v1.Number
	7,  // 4: protos.fields.v1.Field.checkbox:type_name -> protos.fields.v1.Checkbox
	2,  // 5: protos.fields.v1.Base.validator:type_name -> protos.fields.v1.Validator
	3,  // 6: protos.fields.v1.Text.base:type_name -> protos.fields.v1.Base
	3,  // 7: protos.fields.v1.Textarea.base:type_name -> protos.fields.v1.Base
	3,  // 8: protos.fields.v1.Number.base:type_name -> protos.fields.v1.Base
	3,  // 9: protos.fields.v1.Checkbox.base:type_name -> protos.fields.v1.Base
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_fields_v1_fields_proto_init() }
func file_protos_fields_v1_fields_proto_init() {
	if File_protos_fields_v1_fields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_fields_v1_fields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Textarea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fields_v1_fields_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_fields_v1_fields_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Field_Text)(nil),
		(*Field_Textarea)(nil),
		(*Field_Number)(nil),
		(*Field_Checkbox)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_fields_v1_fields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_fields_v1_fields_proto_goTypes,
		DependencyIndexes: file_protos_fields_v1_fields_proto_depIdxs,
		MessageInfos:      file_protos_fields_v1_fields_proto_msgTypes,
	}.Build()
	File_protos_fields_v1_fields_proto = out.File
	file_protos_fields_v1_fields_proto_rawDesc = nil
	file_protos_fields_v1_fields_proto_goTypes = nil
	file_protos_fields_v1_fields_proto_depIdxs = nil
}
