// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: plugin/proto/v1/base.proto

package proto

import (
	v1 "github.com/contaim/sdk/protos/hclspec/v1"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PluginRuntime int32

const (
	PluginRuntime_PLUGIN_RUNTIME_UNSPECIFIED PluginRuntime = 0
	PluginRuntime_PLUGIN_RUNTIME_DAEMON      PluginRuntime = 1
	PluginRuntime_PLUGIN_RUNTIME_SERVER      PluginRuntime = 3
)

// Enum value maps for PluginRuntime.
var (
	PluginRuntime_name = map[int32]string{
		0: "PLUGIN_RUNTIME_UNSPECIFIED",
		1: "PLUGIN_RUNTIME_DAEMON",
		3: "PLUGIN_RUNTIME_SERVER",
	}
	PluginRuntime_value = map[string]int32{
		"PLUGIN_RUNTIME_UNSPECIFIED": 0,
		"PLUGIN_RUNTIME_DAEMON":      1,
		"PLUGIN_RUNTIME_SERVER":      3,
	}
)

func (x PluginRuntime) Enum() *PluginRuntime {
	p := new(PluginRuntime)
	*p = x
	return p
}

func (x PluginRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_v1_base_proto_enumTypes[0].Descriptor()
}

func (PluginRuntime) Type() protoreflect.EnumType {
	return &file_plugin_proto_v1_base_proto_enumTypes[0]
}

func (x PluginRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginRuntime.Descriptor instead.
func (PluginRuntime) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{0}
}

type DaemonPluginType int32

const (
	DaemonPluginType_DAEMON_PLUGIN_TYPE_UNSPECIFIED DaemonPluginType = 0
	DaemonPluginType_DAEMON_PLUGIN_TYPE_DRIVER      DaemonPluginType = 1
)

// Enum value maps for DaemonPluginType.
var (
	DaemonPluginType_name = map[int32]string{
		0: "DAEMON_PLUGIN_TYPE_UNSPECIFIED",
		1: "DAEMON_PLUGIN_TYPE_DRIVER",
	}
	DaemonPluginType_value = map[string]int32{
		"DAEMON_PLUGIN_TYPE_UNSPECIFIED": 0,
		"DAEMON_PLUGIN_TYPE_DRIVER":      1,
	}
)

func (x DaemonPluginType) Enum() *DaemonPluginType {
	p := new(DaemonPluginType)
	*p = x
	return p
}

func (x DaemonPluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonPluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_v1_base_proto_enumTypes[1].Descriptor()
}

func (DaemonPluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_v1_base_proto_enumTypes[1]
}

func (x DaemonPluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonPluginType.Descriptor instead.
func (DaemonPluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{1}
}

type ServerPluginType int32

const (
	ServerPluginType_SERVER_PLUGIN_TYPE_UNSPECIFIED ServerPluginType = 0
	ServerPluginType_SERVER_PLUGIN_TYPE_BUILDER     ServerPluginType = 1
)

// Enum value maps for ServerPluginType.
var (
	ServerPluginType_name = map[int32]string{
		0: "SERVER_PLUGIN_TYPE_UNSPECIFIED",
		1: "SERVER_PLUGIN_TYPE_BUILDER",
	}
	ServerPluginType_value = map[string]int32{
		"SERVER_PLUGIN_TYPE_UNSPECIFIED": 0,
		"SERVER_PLUGIN_TYPE_BUILDER":     1,
	}
)

func (x ServerPluginType) Enum() *ServerPluginType {
	p := new(ServerPluginType)
	*p = x
	return p
}

func (x ServerPluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerPluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_v1_base_proto_enumTypes[2].Descriptor()
}

func (ServerPluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_v1_base_proto_enumTypes[2]
}

func (x ServerPluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerPluginType.Descriptor instead.
func (ServerPluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{2}
}

type PluginInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{0}
}

type PluginInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runtime           PluginRuntime    `protobuf:"varint,1,opt,name=runtime,proto3,enum=plugin.proto.v1.PluginRuntime" json:"runtime,omitempty"`
	DaemonType        DaemonPluginType `protobuf:"varint,2,opt,name=daemon_type,json=daemonType,proto3,enum=plugin.proto.v1.DaemonPluginType" json:"daemon_type,omitempty"`
	ServerType        ServerPluginType `protobuf:"varint,3,opt,name=server_type,json=serverType,proto3,enum=plugin.proto.v1.ServerPluginType" json:"server_type,omitempty"`
	PluginApiVersions []string         `protobuf:"bytes,4,rep,name=plugin_api_versions,json=pluginApiVersions,proto3" json:"plugin_api_versions,omitempty"`
	PluginVersion     string           `protobuf:"bytes,5,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Name              string           `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfoResponse) GetRuntime() PluginRuntime {
	if x != nil {
		return x.Runtime
	}
	return PluginRuntime_PLUGIN_RUNTIME_UNSPECIFIED
}

func (x *PluginInfoResponse) GetDaemonType() DaemonPluginType {
	if x != nil {
		return x.DaemonType
	}
	return DaemonPluginType_DAEMON_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginInfoResponse) GetServerType() ServerPluginType {
	if x != nil {
		return x.ServerType
	}
	return ServerPluginType_SERVER_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginInfoResponse) GetPluginApiVersions() []string {
	if x != nil {
		return x.PluginApiVersions
	}
	return nil
}

func (x *PluginInfoResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConfigSchemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{2}
}

type ConfigSchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *v1.Spec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSchemaResponse) GetSpec() *v1.Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DaemonConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver *DaemonDriverConfig `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
}

func (x *DaemonConfig) Reset() {
	*x = DaemonConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfig) ProtoMessage() {}

func (x *DaemonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConfig.ProtoReflect.Descriptor instead.
func (*DaemonConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonConfig) GetDriver() *DaemonDriverConfig {
	if x != nil {
		return x.Driver
	}
	return nil
}

type DaemonDriverConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DaemonDriverConfig) Reset() {
	*x = DaemonDriverConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonDriverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonDriverConfig) ProtoMessage() {}

func (x *DaemonDriverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonDriverConfig.ProtoReflect.Descriptor instead.
func (*DaemonDriverConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{5}
}

type ServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builder *ServerBuilderConfig `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{6}
}

func (x *ServerConfig) GetBuilder() *ServerBuilderConfig {
	if x != nil {
		return x.Builder
	}
	return nil
}

type ServerBuilderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerBuilderConfig) Reset() {
	*x = ServerBuilderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerBuilderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerBuilderConfig) ProtoMessage() {}

func (x *ServerBuilderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerBuilderConfig.ProtoReflect.Descriptor instead.
func (*ServerBuilderConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{7}
}

type SetConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaemonRuntimeConfig *DaemonConfig `protobuf:"bytes,1,opt,name=daemon_runtime_config,json=daemonRuntimeConfig,proto3" json:"daemon_runtime_config,omitempty"`
	ServerRuntimeConfig *ServerConfig `protobuf:"bytes,2,opt,name=server_runtime_config,json=serverRuntimeConfig,proto3" json:"server_runtime_config,omitempty"`
	PluginConfig        []byte        `protobuf:"bytes,3,opt,name=plugin_config,json=pluginConfig,proto3" json:"plugin_config,omitempty"`
	PluginApiVersion    string        `protobuf:"bytes,4,opt,name=plugin_api_version,json=pluginApiVersion,proto3" json:"plugin_api_version,omitempty"`
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{8}
}

func (x *SetConfigRequest) GetDaemonRuntimeConfig() *DaemonConfig {
	if x != nil {
		return x.DaemonRuntimeConfig
	}
	return nil
}

func (x *SetConfigRequest) GetServerRuntimeConfig() *ServerConfig {
	if x != nil {
		return x.ServerRuntimeConfig
	}
	return nil
}

func (x *SetConfigRequest) GetPluginConfig() []byte {
	if x != nil {
		return x.PluginConfig
	}
	return nil
}

func (x *SetConfigRequest) GetPluginApiVersion() string {
	if x != nil {
		return x.PluginApiVersion
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_v1_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_v1_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_v1_base_proto_rawDescGZIP(), []int{9}
}

var File_plugin_proto_v1_base_proto protoreflect.FileDescriptor

var file_plugin_proto_v1_base_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x68, 0x63, 0x6c, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x13, 0x0a, 0x11, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xc1, 0x02, 0x0a, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x07, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a,
	0x13, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x43, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x68,
	0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x22, 0x4b, 0x0a, 0x0c, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x3b, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x4e, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3e, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x8b,
	0x02, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x15, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x13, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x51, 0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2c,
	0x0a, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x65, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x55, 0x4e,
	0x54, 0x49, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x55, 0x4e,
	0x54, 0x49, 0x4d, 0x45, 0x5f, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x19, 0x0a,
	0x15, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x55, 0x4e, 0x54, 0x49, 0x4d, 0x45, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x55, 0x0a, 0x10, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x1e,
	0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1d, 0x0a, 0x19, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x55, 0x47, 0x49,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x10, 0x01, 0x2a,
	0x56, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x50, 0x4c,
	0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x5f, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x55,
	0x49, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x01, 0x32, 0xa1, 0x02, 0x0a, 0x11, 0x42, 0x61, 0x73, 0x65,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a,
	0x0a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_proto_v1_base_proto_rawDescOnce sync.Once
	file_plugin_proto_v1_base_proto_rawDescData = file_plugin_proto_v1_base_proto_rawDesc
)

func file_plugin_proto_v1_base_proto_rawDescGZIP() []byte {
	file_plugin_proto_v1_base_proto_rawDescOnce.Do(func() {
		file_plugin_proto_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_proto_v1_base_proto_rawDescData)
	})
	return file_plugin_proto_v1_base_proto_rawDescData
}

var file_plugin_proto_v1_base_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_proto_v1_base_proto_goTypes = []interface{}{
	(PluginRuntime)(0),           // 0: plugin.proto.v1.PluginRuntime
	(DaemonPluginType)(0),        // 1: plugin.proto.v1.DaemonPluginType
	(ServerPluginType)(0),        // 2: plugin.proto.v1.ServerPluginType
	(*PluginInfoRequest)(nil),    // 3: plugin.proto.v1.PluginInfoRequest
	(*PluginInfoResponse)(nil),   // 4: plugin.proto.v1.PluginInfoResponse
	(*ConfigSchemaRequest)(nil),  // 5: plugin.proto.v1.ConfigSchemaRequest
	(*ConfigSchemaResponse)(nil), // 6: plugin.proto.v1.ConfigSchemaResponse
	(*DaemonConfig)(nil),         // 7: plugin.proto.v1.DaemonConfig
	(*DaemonDriverConfig)(nil),   // 8: plugin.proto.v1.DaemonDriverConfig
	(*ServerConfig)(nil),         // 9: plugin.proto.v1.ServerConfig
	(*ServerBuilderConfig)(nil),  // 10: plugin.proto.v1.ServerBuilderConfig
	(*SetConfigRequest)(nil),     // 11: plugin.proto.v1.SetConfigRequest
	(*SetConfigResponse)(nil),    // 12: plugin.proto.v1.SetConfigResponse
	(*v1.Spec)(nil),              // 13: protos.hclspec.v1.Spec
}
var file_plugin_proto_v1_base_proto_depIdxs = []int32{
	0,  // 0: plugin.proto.v1.PluginInfoResponse.runtime:type_name -> plugin.proto.v1.PluginRuntime
	1,  // 1: plugin.proto.v1.PluginInfoResponse.daemon_type:type_name -> plugin.proto.v1.DaemonPluginType
	2,  // 2: plugin.proto.v1.PluginInfoResponse.server_type:type_name -> plugin.proto.v1.ServerPluginType
	13, // 3: plugin.proto.v1.ConfigSchemaResponse.spec:type_name -> protos.hclspec.v1.Spec
	8,  // 4: plugin.proto.v1.DaemonConfig.driver:type_name -> plugin.proto.v1.DaemonDriverConfig
	10, // 5: plugin.proto.v1.ServerConfig.builder:type_name -> plugin.proto.v1.ServerBuilderConfig
	7,  // 6: plugin.proto.v1.SetConfigRequest.daemon_runtime_config:type_name -> plugin.proto.v1.DaemonConfig
	9,  // 7: plugin.proto.v1.SetConfigRequest.server_runtime_config:type_name -> plugin.proto.v1.ServerConfig
	3,  // 8: plugin.proto.v1.BasePluginService.PluginInfo:input_type -> plugin.proto.v1.PluginInfoRequest
	5,  // 9: plugin.proto.v1.BasePluginService.ConfigSchema:input_type -> plugin.proto.v1.ConfigSchemaRequest
	11, // 10: plugin.proto.v1.BasePluginService.SetConfig:input_type -> plugin.proto.v1.SetConfigRequest
	4,  // 11: plugin.proto.v1.BasePluginService.PluginInfo:output_type -> plugin.proto.v1.PluginInfoResponse
	6,  // 12: plugin.proto.v1.BasePluginService.ConfigSchema:output_type -> plugin.proto.v1.ConfigSchemaResponse
	12, // 13: plugin.proto.v1.BasePluginService.SetConfig:output_type -> plugin.proto.v1.SetConfigResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_proto_v1_base_proto_init() }
func file_plugin_proto_v1_base_proto_init() {
	if File_plugin_proto_v1_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_proto_v1_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSchemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonDriverConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerBuilderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_v1_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_proto_v1_base_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_v1_base_proto_goTypes,
		DependencyIndexes: file_plugin_proto_v1_base_proto_depIdxs,
		EnumInfos:         file_plugin_proto_v1_base_proto_enumTypes,
		MessageInfos:      file_plugin_proto_v1_base_proto_msgTypes,
	}.Build()
	File_plugin_proto_v1_base_proto = out.File
	file_plugin_proto_v1_base_proto_rawDesc = nil
	file_plugin_proto_v1_base_proto_goTypes = nil
	file_plugin_proto_v1_base_proto_depIdxs = nil
}
