// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: protos/attribute/v1/attribute.proto

package attribute

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Attribute is used as an attribute with optional units.
type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Attribute_FloatVal
	//	*Attribute_IntVal
	//	*Attribute_StringVal
	//	*Attribute_BoolVal
	Value isAttribute_Value `protobuf_oneof:"value"`
	// unit is the unit type, such as MB, GB, etc.
	Unit string `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_attribute_v1_attribute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_protos_attribute_v1_attribute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_protos_attribute_v1_attribute_proto_rawDescGZIP(), []int{0}
}

func (m *Attribute) GetValue() isAttribute_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Attribute) GetFloatVal() float64 {
	if x, ok := x.GetValue().(*Attribute_FloatVal); ok {
		return x.FloatVal
	}
	return 0
}

func (x *Attribute) GetIntVal() int64 {
	if x, ok := x.GetValue().(*Attribute_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *Attribute) GetStringVal() string {
	if x, ok := x.GetValue().(*Attribute_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (x *Attribute) GetBoolVal() bool {
	if x, ok := x.GetValue().(*Attribute_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (x *Attribute) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type isAttribute_Value interface {
	isAttribute_Value()
}

type Attribute_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,1,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Attribute_IntVal struct {
	IntVal int64 `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Attribute_StringVal struct {
	StringVal string `protobuf:"bytes,3,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type Attribute_BoolVal struct {
	BoolVal bool `protobuf:"varint,4,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

func (*Attribute_FloatVal) isAttribute_Value() {}

func (*Attribute_IntVal) isAttribute_Value() {}

func (*Attribute_StringVal) isAttribute_Value() {}

func (*Attribute_BoolVal) isAttribute_Value() {}

var File_protos_attribute_v1_attribute_proto protoreflect.FileDescriptor

var file_protos_attribute_v1_attribute_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xa0, 0x01, 0x0a, 0x09, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x08, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x56,
	0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_attribute_v1_attribute_proto_rawDescOnce sync.Once
	file_protos_attribute_v1_attribute_proto_rawDescData = file_protos_attribute_v1_attribute_proto_rawDesc
)

func file_protos_attribute_v1_attribute_proto_rawDescGZIP() []byte {
	file_protos_attribute_v1_attribute_proto_rawDescOnce.Do(func() {
		file_protos_attribute_v1_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_attribute_v1_attribute_proto_rawDescData)
	})
	return file_protos_attribute_v1_attribute_proto_rawDescData
}

var file_protos_attribute_v1_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_attribute_v1_attribute_proto_goTypes = []interface{}{
	(*Attribute)(nil), // 0: protos.attribute.v1.Attribute
}
var file_protos_attribute_v1_attribute_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_attribute_v1_attribute_proto_init() }
func file_protos_attribute_v1_attribute_proto_init() {
	if File_protos_attribute_v1_attribute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_attribute_v1_attribute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_attribute_v1_attribute_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Attribute_FloatVal)(nil),
		(*Attribute_IntVal)(nil),
		(*Attribute_StringVal)(nil),
		(*Attribute_BoolVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_attribute_v1_attribute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_attribute_v1_attribute_proto_goTypes,
		DependencyIndexes: file_protos_attribute_v1_attribute_proto_depIdxs,
		MessageInfos:      file_protos_attribute_v1_attribute_proto_msgTypes,
	}.Build()
	File_protos_attribute_v1_attribute_proto = out.File
	file_protos_attribute_v1_attribute_proto_rawDesc = nil
	file_protos_attribute_v1_attribute_proto_goTypes = nil
	file_protos_attribute_v1_attribute_proto_depIdxs = nil
}
